@startuml

title GoTech 2022 Conference - Use Cases Diagram
left to right direction
skinparam actorStyle awesome
skinparam actorFontColor blue
skinparam usecase {
backgroundColor OrangeRed
fontColor white
}
skinparam rectangle {
fontColor white
}


:EventOrganizer: as EA #Purple
:EventPartner: as EP  #Green
actor PartnerBrandingTeam as EPB #Blue
actor Participant as P #Gold
actor :Speaker: as S #LightBlue

EPB -up-|> EP
EA <..> EPB : session content #Blue
EPB <..> S : presentation paper #Blue

rectangle "go>tech" as GT #Purple {
usecase (Manage Events's Venue Location) as ML
usecase (Manage Events's Partners) as MP
usecase (Manage Events's Venues Exhibitors) as ME
usecase (Manage Events's Content Stages) as MS
usecase (Manage Events's Agenda Sessions) as MA
usecase (Manage Events's Digital Headliners) as MH
usecase (Manage Events's Participants) as MV
usecase (Monitor Events's Online Platform) as MoP
usecase (Participate Event's  Exhibitions) as PoE
usecase (Participate Event's Stage) as PoS
EA -right-> ML #Red
EA -right-> MP #Red
EA -right-> ME #Red
EA -right-> MS #Red
EA -right-> MA #Red
EA -right-> MH #Red
EA -right-> MV #Red
EA -right-> MoP #Red
EP .right.> MoP #Green
EP .right.> PoE #Green
P ..up..> MoP
P ..up..> PoE
P ..up..> PoS
EPB ..up..> PoE
EPB ..up..> MoP
S ..left..> MoP
S -left-> PoS #Blue
S ..left..> PoE
}

@enduml